/**
 * LeetCode 389. Find the Difference
 * https://leetcode.com/problems/find-the-difference/
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then adding one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 */

function findTheDifference(s: string, t: string): string {
  const sChars: Record<string, number> = {};
  const tChars: Record<string, number> = {};

  for (let i = 0; i < t.length; i++) {
    if (!sChars[s.charAt(i)]) {
      sChars[s.charAt(i)] = 1;
    } else {
      sChars[s.charAt(i)] += 1;
    }

    if (t.charAt(i)) {
      if (!tChars[t.charAt(i)]) {
        tChars[t.charAt(i)] = 1;
      } else {
        tChars[t.charAt(i)] += 1;
      }
    }
  }

  for (const key in tChars) {
    if (!sChars[key]) {
      return key;
    }

    if (sChars[key] !== tChars[key]) {
      return key;
    }
  }

  return "";
}

export { findTheDifference };
